name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.18
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Build Hugo 
        run: hugo --minify

      - name: Deploy to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.OCTAVIA_4_ROOT_ACCESS }}
          cname: glossary.airbyte.com
