name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.17
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Checkout python
        uses: actions/checkout@v2
      # Setup steps
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.11"

      - name: pwd
        run: pwd

      - name: ls
        run: ls -l content/term
      - name: ls
        run: ls -l public

      - name: ls
        run: ls -l public/indices

      - name: Convert links to lower case
        run: python3 lower_case.py

      - name: ls
        run: ls -l content/term

      - name: Build again after changing to lower case
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
          cname: glossary.airbyte.com # without trailing slash #https://airbytehq.github.io/brain
